WIP Migrate 3b exposures
informatics-lab/DIMEX pull request #16
Opened 2023-02-03 11:43 UTC by natalietf

Extracting functions from `3b_Exposures_Q1_2021.R`.

Steps (copied Pete's steps):
- [ ] Extract relevant code and add to R package
- [ ] Create tests
- [ ] Create docs

Have just started extracting code to R package, created `calculate_exposure` function. Still need to create another function for merging of PM2.5 data at start of R script.

2023-02-03 13:32 UTC, DPeterK reviewed
@natalietf this looks great! As I've commented throughout, however, I think you've gone one step further than we need right now by also starting to make improvements to the code as well as lifting and shifting it. As such I'd recommend backing out the improvements and just move Matt's original code as-is for now.

That said, I don't think any of the code improvements you've made here are in any way wasted as we can use the code in its current state as the starting point for making improvements to it once we're happy with the original move of the code 👍

2023-02-03 13:32 UTC, DPeterK commented on R/calculate_exposure.R
> +estimate_exposures <- function(actvities_complete, pop_dat, pm25_ctm, num_date_start, num_date_end) {
You might be able to get away with assuming that all these variables you're passing in as arguments already exist in the R environment, so don't need to be explicitly passed into the function. That's the route I've gone down in my case, but it will be interesting to get input from @andrewgryan on this too.

2023-02-03 13:32 UTC, DPeterK commented on R/calculate_exposure.R
> +             as.numeric(date) <= num_date_end) %>%
We'll probably want to do this in future (and, very likely regardless of my previous comment, pass start and end date as arguments to the function) but I think initially we want to keep the code shifted as close to the original code as possible. This, among other things, will make it simpler to confirm that our changes haven't affected how the code runs!

2023-02-03 13:32 UTC, DPeterK commented on R/calculate_exposure.R
> +  for (i in 1:3){
Undoubtedly this is an improvement over Matt's original code (you've factored out repeated code, hooray!) but again it means we're lifting, shifting and modifying rather than just lifting and shifting. Again I'd suggest that we move the code as-is and get making valid improvements like this once we're happy with the original lift and shift.

And, for when we get to it, I think you could probably simplify L30 & L32 together into something like the following:
```R
for (ambient in c("pm25_cams_agg", "pm25_emep_agg", "pm25_five")) {
```
and then reference `ambient` in place of `ambient_list[i]` throughout the loop.

2023-02-03 13:32 UTC, DPeterK commented on R/calculate_exposure.R
> +    activities_complete <- calculate_household(act_dat = activities_complete, pop_dat = pop_dat,
I take it that these three calculate functions have been migrated already..?

2023-02-03 14:09 UTC, andrewgryan commented on R/calculate_exposure.R
> +    activities_complete <- calculate_household(act_dat = activities_complete, pop_dat = pop_dat,
Yep, already migrated them in a previous PR

2023-02-03 14:13 UTC, andrewgryan commented on R/calculate_exposure.R
> +  for (i in 1:3){
I don't think we will need to loop over i to reduce the duplication. I probably should have been clearer on how best to remove the duplication. As @DPeterK suggests, this PR should just be the lift/shift operation and the next PR will be the reshape the table columns to accomodate meta-data for each "scenario". The calculations will then be vectorised to achieve the same result.

2023-02-03 14:17 UTC, andrewgryan commented on R/calculate_exposure.R
> +estimate_exposures <- function(actvities_complete, pop_dat, pm25_ctm, num_date_start, num_date_end) {
I think those ones are needed to execute the body of the extracted function. They won't be in the environment by default.

2023-02-03 14:20 UTC, andrewgryan commented on R/calculate_exposure.R
> +             as.numeric(date) <= num_date_end) %>%
@natalietf the numeric nature of the dates are something we should tackle in a follow on PR. Ideally, the user facing interface will allow dates and inside the code the mapping to integer will take place if needed. For now, focus on the lift/shift operation and keep track of the next steps needed to make the extracted code more human friendly

2023-02-03 14:30 UTC, andrewgryan requested changes
This needs a few changes, it seems to be doing 3 PRs worth of effort while missing a few details of the first step.

1. Revert to just Matt's code moved into a function
2. Match the file and function name in R/, e.g. `R/estimate_exposure.R` and `estimate_exposure <- function...`
3. Use `usethis::use_test("estimate_exposure")` to scaffold out a test that calls `estimate_exposure` with minimal data

2023-02-03 14:45 UTC, natalietf commented on R/calculate_exposure.R
> +             as.numeric(date) <= num_date_end) %>%
Sounds good! Have reverted it back to how it was for now so we can work on it later

2023-02-06 15:45 UTC, DPeterK reviewed
@natalietf this is looking much better now 👍 I think the test needs to be extended to test that data values from the function match expected values, and you'll need to update the docs as well to include our new function's documentation (using `devtools::document()`).

2023-02-06 15:45 UTC, DPeterK commented on R/estimate_exposures.R
> +             as.numeric(date) <= 18717) %>%
This isn't at all a problem for this PR, but this line is all sorts of concerning - assumedly `as.numeric` converts a date into a `days since epoch` integer? But how do we know what the epoch is, what the calendar is (e.g. is it 365 day, 366 day, Julian, Gregorian, ...), and whether any of those unknowns will remain consistent?

2023-02-06 15:45 UTC, DPeterK commented on tests/testthat/test-estimate_exposures.R
> +                        agegr4_label = c("<16", "<16"),
Ideally this test data would be internally consistent - that is, your `agegr4` indices change, but your `agegr4_label`s do not...

2023-02-06 15:45 UTC, DPeterK commented on tests/testthat/test-estimate_exposures.R
> +                                    date = as.Date("2020-12-20"),
I take it this value falls within the interval defined in the function!

2023-02-06 15:45 UTC, DPeterK commented on tests/testthat/test-estimate_exposures.R
> +  expect_equal(actual_colnames, expected_colnames)
I think we want to modify this test to confirm that the entire dataframe `actual` is equal to a new dataframe `expected`. That way, we can see if changes we make to the code cause numeric changes to the data values it generates, and react accordingly.

2023-02-06 15:48 UTC, natalietf commented on tests/testthat/test-estimate_exposures.R
> +  expect_equal(actual_colnames, expected_colnames)
Thanks Pete! Yes I agree! seem to be getting some strange NaN values in the dataframe still :( once I've worked them out I can hopefully have an `expected` dataframe to compare to

2023-02-07 09:39 UTC, natalietf commented on tests/testthat/test-estimate_exposures.R
> +  actual$pm25_five_hhd <- round(actual$pm25_five_hhd, 2)
Was struggling to get a successful test as the test would fail and return back the `expected` result to an extra decimal place each time. I'm not sure if this is the best solution for this...? But left it as a temporary way to get a passing test

2023-02-07 09:49 UTC, natalietf commented on R/estimate_exposures.R
> +             as.numeric(date) <= 18717) %>%
Yeah I was curious so looked it up yesterday and it is days since Unix Epoch ("1970-01-01") - think you can alternatively specify an `origin`. 
Good question about the calendars though... I hadn't thought about that...

2023-02-07 10:10 UTC, natalietf commented on tests/testthat/test-estimate_exposures.R
> +  actual[, exposures] <- round(actual[, exposures], 2)
Was struggling to get a successful test as the test would fail and return back the expected result to an extra decimal place each time. I'm not sure if this is the best solution for this...? But left it as a temporary way to get a passing test

2023-02-08 11:27 UTC, andrewgryan commented
@DPeterK can we also bank this?

2023-02-08 13:32 UTC, DPeterK approved these changes

2023-02-08 13:32 UTC, DPeterK commented
@andrewgryan I'm happy with this - so long as you're happy with the rounding shim that @natalietf has added to constrain test results to 2DP.

2023-02-08 13:35 UTC, DPeterK commented
@natalietf all that's needed now is to resolve the conflict in the `NAMESPACE` file - I just took a quick look and it's not a tricky resolution. You'll just need to ensure that all the lines from the `development` branch and that you've added here are present in the result (and that the function names are ordered alphabetically!), and that the lines beginning with `<<<` / `>>>` (which indicate where the conflict is) are removed.

2023-02-08 13:57 UTC, natalietf commented
> @natalietf all that's needed now is to resolve the conflict in the `NAMESPACE` file - I just took a quick look and it's not a tricky resolution. You'll just need to ensure that all the lines from the `development` branch and that you've added here are present in the result (and that the function names are ordered alphabetically!), and that the lines beginning with `<<<` / `>>>` (which indicate where the conflict is) are removed.

Got it! thanks @DPeterK !!

2023-02-09 15:37 UTC, merged